# Generated by Django 5.2.13 on 2026-04-20 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="gpt-4o",
                        help_text="使用的 AI 模型名称，如 gpt-4o / gpt-4o-mini",
                        max_length=64,
                        verbose_name="AI 模型",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="留空则使用系统默认 Key",
                        max_length=256,
                        verbose_name="OpenAI API Key",
                    ),
                ),
                (
                    "openai_base_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="留空则使用默认的 https://api.openai.com/v1",
                        max_length=256,
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh", max_length=16, verbose_name="界面语言"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
