# Generated by Django 5.2.13 on 2026-04-25 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_nickname_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ai_model",
            field=models.CharField(
                default="ark-doubao-smart-router",
                help_text="模型目录键，如 ark-doubao-smart-router（对话/画布与 ai_model_catalog 一致）",
                max_length=64,
                verbose_name="AI 模型",
            ),
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("google", "Google"),
                            ("qq", "QQ"),
                        ],
                        max_length=20,
                        verbose_name="OAuth 提供商",
                    ),
                ),
                (
                    "provider_user_id",
                    models.CharField(max_length=255, verbose_name="第三方用户 ID"),
                ),
                (
                    "provider_username",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="第三方用户名",
                    ),
                ),
                (
                    "provider_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="第三方邮箱",
                    ),
                ),
                (
                    "provider_avatar_url",
                    models.URLField(
                        blank=True, default="", verbose_name="第三方头像 URL"
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, default="", verbose_name="Access Token（加密存储）"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, default="", verbose_name="Refresh Token（加密存储）"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Token 过期时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方账号",
                "verbose_name_plural": "第三方账号",
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_user_id"],
                        name="accounts_so_provide_71a274_idx",
                    ),
                    models.Index(
                        fields=["user", "provider"],
                        name="accounts_so_user_id_0a462a_idx",
                    ),
                ],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
    ]
