"""
方舟 / 火山文档中的模型种子数据（供迁移与可选的 ``sync_aimodel_catalog`` 使用）。

说明：不含任何密钥；仅描述与 ``catalog_key`` / ``model_id`` 等元数据。
修改后已部署环境需通过 Admin、API 或重新跑迁移逻辑同步数据库。
"""

from __future__ import annotations

from typing import Any

# 画布 LLM 节点：五种全选
_ALL = ["chat", "text", "image", "audio", "video"]
_NO_IMG = ["chat", "text", "audio", "video"]
_CHAT_TEXT = ["chat", "text"]


def _row(
    *,
    catalog_key: str,
    label: str,
    description: str,
    model_id: str,
    category: str,
    category_label: str,
    category_order: int,
    scopes: list[str],
    scope_summary: str,
    canvas_node_kinds: list[str],
    canvas_universal: bool = False,
    api_kind: str = "ark_chat",
    show_in_canvas_llm_nodes: bool = True,
    route: str = "doubao",
    sort_order: int = 0,
) -> dict[str, Any]:
    return {
        "catalog_key": catalog_key,
        "label": label,
        "description": description,
        "route": route,
        "model_id": model_id,
        "category": category,
        "category_label": category_label,
        "category_order": category_order,
        "scopes": scopes,
        "scope_summary": scope_summary,
        "canvas_node_kinds": canvas_node_kinds,
        "canvas_universal": canvas_universal,
        "api_kind": api_kind,
        "show_in_canvas_llm_nodes": show_in_canvas_llm_nodes,
        "sort_order": sort_order,
        "is_active": True,
    }


# category_order：语言 0–99，向量 100，视觉生成 200，3D 300，语音 400（越大越靠后分组）
CATALOG_SEED_ROWS: list[dict[str, Any]] = [
    _row(
        catalog_key="ark-doubao-smart-router",
        label="豆包 · 智能路由",
        description="Doubao-Smart-Router",
        model_id="Doubao-Smart-Router",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["全节点", "自动选模"],
        scope_summary="智能路由：按任务自动匹配最优模型；所有带模型画布节点可选。",
        canvas_node_kinds=[],
        canvas_universal=True,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-doubao-video-script-llm",
        label="视频脚本 / 分镜与旁白（LLM）",
        description="视频节点专用文案：分镜、旁白、镜头描述",
        model_id="",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["分镜", "旁白", "镜头表", "动态描述"],
        scope_summary="仅出现在「视频」节点：输出为文字分镜/旁白/镜头描述。说明：当前画布视频节点走方舟对话接口，"
        "不直接生成 mp4；像素级文生视频请在火山控制台开通 Seedance 等后走专用视频 API。",
        canvas_node_kinds=["video"],
        sort_order=4,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-pro",
        label="豆包 Seed 2.0 Pro",
        description="Doubao-Seed-2.0-pro",
        model_id="Doubao-Seed-2.0-pro",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["旗舰", "复杂推理", "代码", "多轮"],
        scope_summary="旗舰通用：强逻辑与复杂任务、对话、文案、代码与多轮规划。",
        canvas_node_kinds=list(_ALL),
        sort_order=10,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-lite",
        label="豆包 Seed 2.0 Lite",
        description="Doubao-Seed-2.0-lite",
        model_id="Doubao-Seed-2.0-lite",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量", "高性价比"],
        scope_summary="轻量通用：低延迟、日常对话与快速生成。",
        canvas_node_kinds=list(_ALL),
        sort_order=11,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-mini",
        label="豆包 Seed 2.0 Mini",
        description="Doubao-Seed-2.0-mini",
        model_id="Doubao-Seed-2.0-mini",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["超轻量", "高频"],
        scope_summary="超轻量：高频问答、客服、轻量文本；不适合复杂看图描述。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=12,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-code",
        label="豆包 Seed 2.0 Code",
        description="Doubao-Seed-2.0-Code",
        model_id="Doubao-Seed-2.0-Code",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "调试", "注释"],
        scope_summary="代码专用：生成、排错、解释与注释。",
        canvas_node_kinds=list(_ALL),
        sort_order=13,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-8",
        label="豆包 Seed 1.8",
        description="Doubao-Seed-1.8",
        model_id="Doubao-Seed-1.8",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["通用", "平衡"],
        scope_summary="通用对话：性能与成本平衡，适合日常创作与问答。",
        canvas_node_kinds=list(_ALL),
        sort_order=14,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-lite",
        label="豆包 Seed 1.6 Lite",
        description="Doubao-Seed-1.6-lite",
        model_id="Doubao-Seed-1.6-lite",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量对话"],
        scope_summary="轻量对话与基础文本处理。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=15,
    ),
    _row(
        catalog_key="ark-doubao-seed-character",
        label="豆包 Seed Character",
        description="Doubao-Seed-Character",
        model_id="Doubao-Seed-Character",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["角色扮演", "人设", "NPC"],
        scope_summary="角色对话：需人设描述，输出符合角色的文本。",
        canvas_node_kinds=list(_CHAT_TEXT),
        sort_order=16,
    ),
    _row(
        catalog_key="ark-doubao-seed-code",
        label="豆包 Seed Code",
        description="Doubao-Seed-Code",
        model_id="Doubao-Seed-Code",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "Bug 修复"],
        scope_summary="通用代码模型：多语言开发与解释。",
        canvas_node_kinds=list(_CHAT_TEXT),
        sort_order=17,
    ),
    _row(
        catalog_key="ark-glm-4-7",
        label="GLM-4.7",
        description="智谱 GLM-4.7",
        model_id="GLM-4.7",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["长文本", "创作", "多轮"],
        scope_summary="智谱通用大模型：理解与创作、复杂对话与长文本。",
        canvas_node_kinds=list(_ALL),
        sort_order=20,
    ),
    _row(
        catalog_key="ark-deepseek-v3-2",
        label="DeepSeek-V3.2",
        description="DeepSeek-V3.2",
        model_id="DeepSeek-V3.2",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["数学", "逻辑", "推理"],
        scope_summary="强逻辑与数学推理、复杂任务处理。",
        canvas_node_kinds=list(_ALL),
        sort_order=21,
    ),
    # --- 向量 ---
    _row(
        catalog_key="ark-doubao-embedding",
        label="豆包 Embedding",
        description="Doubao-embedding",
        model_id="Doubao-embedding",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["RAG", "语义检索"],
        scope_summary="文本向量嵌入；方舟 v3 同一密钥，用于知识库与相似度。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-doubao-embedding-large",
        label="豆包 Embedding Large",
        description="Doubao-embedding-large",
        model_id="Doubao-embedding-large",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["高精度", "长文本"],
        scope_summary="大维度文本嵌入，更高语义精度。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=1,
    ),
    _row(
        catalog_key="ark-doubao-embedding-vision",
        label="豆包 Embedding Vision",
        description="Doubao-embedding-vision",
        model_id="Doubao-embedding-vision",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["多模态", "以图搜图"],
        scope_summary="图像+文本多模态嵌入，图文检索。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=2,
    ),
    # --- 视觉生成 / 编辑 ---
    _row(
        catalog_key="ark-seedream-5-0-lite",
        label="Seedream 5.0 Lite",
        description="doubao-seedream-5-0-260128",
        model_id="doubao-seedream-5-0-260128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生图", "图生图"],
        scope_summary="画布「图片」节点文生图：走 Ark images.generate；需与控制台开通的模型 id 一致。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-seedream-4-5",
        label="Seedream 4.5",
        description="doubao-seedream-4-5-251128",
        model_id="doubao-seedream-4-5-251128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高质量", "海报", "电商图"],
        scope_summary="高质量文生图；走 Ark images.generate。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=1,
    ),
    _row(
        catalog_key="ark-seedream-4-0",
        label="Seedream 4.0",
        description="doubao-seedream-4-0-250828",
        model_id="doubao-seedream-4-0-250828",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["稳定", "快速出图"],
        scope_summary="经典文生图；走 Ark images.generate。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=2,
    ),
    _row(
        catalog_key="ark-seededit-3-0-i2i",
        label="SeedEdit 3.0 i2i",
        description="doubao-seededit-3-0-i2i",
        model_id="doubao-seededit-3-0-i2i",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["修图", "扩图", "风格迁移"],
        scope_summary="图生图编辑；画布侧暂未接 images 多图参数，请优先用文生图模型或控制台。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=3,
    ),
    _row(
        catalog_key="ark-seedance-2-0",
        label="Seedance 2.0",
        description="doubao-seedance-2-0-260128",
        model_id="doubao-seedance-2-0-260128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "异步任务"],
        scope_summary="画布「视频」节点文生视频：content_generation.tasks 创建后轮询直至成功。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=9,
    ),
    _row(
        catalog_key="ark-seedance-1-5-pro",
        label="Seedance 1.5 Pro",
        description="doubao-seedance-1-5-pro-251215",
        model_id="doubao-seedance-1-5-pro-251215",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "图生视频"],
        scope_summary="视频生成：短片、动态海报；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=10,
    ),
    _row(
        catalog_key="ark-seedance-1-0-pro-fast",
        label="Seedance 1.0 Pro Fast",
        description="doubao-seedance-1-0-pro-fast-251015",
        model_id="doubao-seedance-1-0-pro-fast-251015",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["低延迟", "短视频"],
        scope_summary="快速视频草稿；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=11,
    ),
    _row(
        catalog_key="ark-seedance-1-0-pro",
        label="Seedance 1.0 Pro",
        description="doubao-seedance-1-0-pro-250528",
        model_id="doubao-seedance-1-0-pro-250528",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高质量视频"],
        scope_summary="高质量视频；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=12,
    ),
    _row(
        catalog_key="ark-seed3d-2-0",
        label="Seed3D 2.0",
        description="Doubao-Seed3D-2.0",
        model_id="Doubao-Seed3D-2.0",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["3D", "文生3D", "图生3D"],
        scope_summary="3D 资产生成：游戏与建模辅助。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=20,
    ),
    _row(
        catalog_key="ark-hyper3d-gen2",
        label="Hyper3D Gen2",
        description="Hyper3D-Gen2",
        model_id="Hyper3D-Gen2",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["3D", "快速资产"],
        scope_summary="轻量化快速 3D 原型。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=21,
    ),
    _row(
        catalog_key="ark-hitem3d-2-0",
        label="Hitem3D 2.0",
        description="Hitem3D-2.0",
        model_id="Hitem3D-2.0",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高精度3D"],
        scope_summary="高精度 3D 与工业设计向素材。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=22,
    ),
    # --- 语音（独立 openspeech 等，不在画布 LLM 下拉展示）---
    _row(
        catalog_key="speech-doubao-tts",
        label="豆包 · 语音合成",
        description="Doubao-语音合成",
        model_id="Doubao-语音合成",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["TTS"],
        scope_summary="基础 TTS；需 openspeech appid+access_token，非方舟 chat 密钥。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=0,
    ),
    _row(
        catalog_key="speech-doubao-voice-clone",
        label="豆包 · 声音复刻",
        description="Doubao-声音复刻",
        model_id="Doubao-声音复刻",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["复刻音色"],
        scope_summary="参考音频生成专属音色；独立语音接口鉴权。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=1,
    ),
    _row(
        catalog_key="speech-doubao-asr-stream",
        label="豆包 · 流式语音识别",
        description="Doubao-流式语音识别",
        model_id="Doubao-流式语音识别",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["ASR", "实时"],
        scope_summary="实时语音转写；独立 ASR 接口。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=2,
    ),
    _row(
        catalog_key="speech-doubao-asr-file",
        label="豆包 · 录音文件识别",
        description="Doubao-录音文件识别",
        model_id="Doubao-录音文件识别",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["离线转写"],
        scope_summary="长音频/批量文件转文字。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=3,
    ),
    _row(
        catalog_key="speech-doubao-simultaneous-2",
        label="豆包 · 同声传译 2.0",
        description="Doubao-同声传译-2.0",
        model_id="Doubao-同声传译-2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["同传", "翻译"],
        scope_summary="实时语音翻译；独立接口与配额。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=4,
    ),
    _row(
        catalog_key="speech-doubao-voice-design",
        label="豆包 · 音色设计",
        description="Doubao-音色设计",
        model_id="Doubao-音色设计",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["音色描述"],
        scope_summary="文本描述生成定制音色。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=5,
    ),
    _row(
        catalog_key="speech-doubao-tts-2",
        label="豆包 · 语音合成 2.0",
        description="Doubao-语音合成-2.0",
        model_id="Doubao-语音合成-2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["TTS", "情感"],
        scope_summary="增强 TTS，更自然情感与语气。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=6,
    ),
    _row(
        catalog_key="speech-doubao-podcast",
        label="豆包 · 语音播客",
        description="Doubao-语音播客",
        model_id="Doubao-语音播客",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["多角色", "播客"],
        scope_summary="剧本/对话生成多角色语音。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=7,
    ),
    _row(
        catalog_key="speech-doubao-asr-file-2",
        label="豆包 · 录音文件识别 2.0",
        description="Doubao-录音文件识别2.0",
        model_id="Doubao-录音文件识别2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["转写", "字幕"],
        scope_summary="增强版离线转写，低延迟高准确率。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=8,
    ),
    _row(
        catalog_key="speech-doubao-realtime-voice",
        label="豆包 · 实时语音交互",
        description="Doubao-实时语音交互",
        model_id="Doubao-实时语音交互",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["端到端", "语音对话"],
        scope_summary="实时语音输入+输出；专属实时接口。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=9,
    ),
]
