"""
方舟 / 火山文档中的模型种子数据（供迁移与可选的 ``sync_aimodel_catalog`` 使用）。

说明：不含任何密钥；仅描述与 ``catalog_key`` / ``model_id`` 等元数据。
修改后已部署环境需通过 Admin、API 或重新跑迁移逻辑同步数据库。
"""

from __future__ import annotations

from typing import Any

# 画布 LLM 节点：五种全选
_ALL = ["chat", "text", "image", "audio", "video"]
_NO_IMG = ["chat", "text", "audio", "video"]
_CHAT_TEXT = ["chat", "text"]


def _row(
    *,
    catalog_key: str,
    label: str,
    description: str,
    model_id: str,
    category: str,
    category_label: str,
    category_order: int,
    scopes: list[str],
    scope_summary: str,
    canvas_node_kinds: list[str],
    canvas_universal: bool = False,
    api_kind: str = "ark_chat",
    show_in_canvas_llm_nodes: bool = True,
    route: str = "doubao",
    sort_order: int = 0,
) -> dict[str, Any]:
    return {
        "catalog_key": catalog_key,
        "label": label,
        "description": description,
        "route": route,
        "model_id": model_id,
        "category": category,
        "category_label": category_label,
        "category_order": category_order,
        "scopes": scopes,
        "scope_summary": scope_summary,
        "canvas_node_kinds": canvas_node_kinds,
        "canvas_universal": canvas_universal,
        "api_kind": api_kind,
        "show_in_canvas_llm_nodes": show_in_canvas_llm_nodes,
        "sort_order": sort_order,
        "is_active": True,
    }


# category_order：语言 0–99，向量 100，视觉生成 200，3D 300，语音 400（越大越靠后分组）
CATALOG_SEED_ROWS: list[dict[str, Any]] = [
    _row(
        catalog_key="ark-doubao-smart-router",
        label="豆包 · 智能路由",
        description="Doubao-Smart-Router",
        model_id="Doubao-Smart-Router",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["全节点", "自动选模"],
        scope_summary="智能路由：按任务自动匹配最优模型；所有带模型画布节点可选。",
        canvas_node_kinds=[],
        canvas_universal=True,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-doubao-video-script-llm",
        label="视频脚本 / 分镜与旁白（LLM）",
        description="视频节点专用文案：分镜、旁白、镜头描述",
        model_id="",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["分镜", "旁白", "镜头表", "动态描述"],
        scope_summary="仅出现在「视频」节点：输出为文字分镜/旁白/镜头描述。说明：当前画布视频节点走方舟对话接口，"
        "不直接生成 mp4；像素级文生视频请在火山控制台开通 Seedance 等后走专用视频 API。",
        canvas_node_kinds=["video"],
        sort_order=4,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-pro",
        label="豆包 Seed 2.0 Pro",
        description="Doubao-Seed-2.0-pro",
        model_id="Doubao-Seed-2.0-pro",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["旗舰", "复杂推理", "代码", "多轮"],
        scope_summary="旗舰通用：强逻辑与复杂任务、对话、文案、代码与多轮规划。",
        canvas_node_kinds=list(_ALL),
        sort_order=10,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-lite",
        label="豆包 Seed 2.0 Lite",
        description="Doubao-Seed-2.0-lite",
        model_id="Doubao-Seed-2.0-lite",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量", "高性价比"],
        scope_summary="轻量通用：低延迟、日常对话与快速生成。",
        canvas_node_kinds=list(_ALL),
        sort_order=11,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-mini",
        label="豆包 Seed 2.0 Mini",
        description="Doubao-Seed-2.0-mini",
        model_id="Doubao-Seed-2.0-mini",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["超轻量", "高频"],
        scope_summary="超轻量：高频问答、客服、轻量文本；不适合复杂看图描述。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=12,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-code",
        label="豆包 Seed 2.0 Code",
        description="Doubao-Seed-2.0-Code",
        model_id="Doubao-Seed-2.0-Code",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "调试", "注释"],
        scope_summary="代码专用：生成、排错、解释与注释。",
        canvas_node_kinds=list(_ALL),
        sort_order=13,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-8",
        label="豆包 Seed 1.8",
        description="Doubao-Seed-1.8",
        model_id="Doubao-Seed-1.8",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["通用", "平衡"],
        scope_summary="通用对话：性能与成本平衡，适合日常创作与问答。",
        canvas_node_kinds=list(_ALL),
        sort_order=14,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-lite",
        label="豆包 Seed 1.6 Lite",
        description="Doubao-Seed-1.6-lite",
        model_id="Doubao-Seed-1.6-lite",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量对话"],
        scope_summary="轻量对话与基础文本处理。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=15,
    ),
    _row(
        catalog_key="ark-doubao-seed-character",
        label="豆包 Seed Character",
        description="Doubao-Seed-Character",
        model_id="Doubao-Seed-Character",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["角色扮演", "人设", "NPC"],
        scope_summary="角色对话：需人设描述，输出符合角色的文本。",
        canvas_node_kinds=list(_CHAT_TEXT),
        sort_order=16,
    ),
    _row(
        catalog_key="ark-doubao-seed-code",
        label="豆包 Seed Code",
        description="Doubao-Seed-Code",
        model_id="Doubao-Seed-Code",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "Bug 修复"],
        scope_summary="通用代码模型：多语言开发与解释。",
        canvas_node_kinds=list(_CHAT_TEXT),
        sort_order=17,
    ),
    _row(
        catalog_key="ark-glm-4-7",
        label="GLM-4.7",
        description="智谱 GLM-4.7",
        model_id="GLM-4.7",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["长文本", "创作", "多轮"],
        scope_summary="智谱通用大模型：理解与创作、复杂对话与长文本。",
        canvas_node_kinds=list(_ALL),
        sort_order=20,
    ),
    _row(
        catalog_key="ark-deepseek-v3-2",
        label="DeepSeek-V3.2",
        description="DeepSeek-V3.2",
        model_id="DeepSeek-V3.2",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["数学", "逻辑", "推理"],
        scope_summary="强逻辑与数学推理、复杂任务处理。",
        canvas_node_kinds=list(_ALL),
        sort_order=21,
    ),
    _row(
        catalog_key="ark-deepseek-v3-1-terminus",
        label="DeepSeek-V3.1-Terminus",
        description="DeepSeek-V3.1-Terminus",
        model_id="DeepSeek-V3.1-Terminus",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["Agent", "代码", "长上下文"],
        scope_summary="V3.1 Terminus 变体；以控制台「复制模型 ID」为准，若与控制台不一致请改目录 model_id。",
        canvas_node_kinds=list(_ALL),
        sort_order=22,
    ),
    _row(
        catalog_key="ark-deepseek-r1-250528",
        label="DeepSeek-R1（250528）",
        description="DeepSeek-R1-250528",
        model_id="DeepSeek-R1-250528",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["推理", "数学", "复杂任务"],
        scope_summary="R1 带日期后缀版本；调用名请以控制台为准。",
        canvas_node_kinds=list(_ALL),
        sort_order=23,
    ),
    _row(
        catalog_key="ark-deepseek-v3-250324",
        label="DeepSeek-V3（250324）",
        description="DeepSeek-V3-250324",
        model_id="DeepSeek-V3-250324",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["通用", "逻辑", "代码"],
        scope_summary="V3 带日期后缀版本；调用名请以控制台为准。",
        canvas_node_kinds=list(_ALL),
        sort_order=24,
    ),
    _row(
        catalog_key="ark-doubao-1-5-thinking-pro-250415",
        label="豆包 1.5 Thinking Pro（250415）",
        description="doubao-1-5-thinking-pro-250415",
        model_id="doubao-1-5-thinking-pro-250415",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["深度思考", "推理", "数学"],
        scope_summary="Thinking 系列；适合复杂推理与长链思考类任务。",
        canvas_node_kinds=list(_ALL),
        sort_order=25,
    ),
    _row(
        catalog_key="ark-doubao-1-5-vision-pro-250328",
        label="豆包 1.5 Vision Pro（250328）",
        description="doubao-1-5-vision-pro-250328",
        model_id="doubao-1-5-vision-pro-250328",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["多模态", "看图", "视频理解"],
        scope_summary="视觉增强对话；画布含图片/视频节点时可选用。",
        canvas_node_kinds=list(_ALL),
        sort_order=26,
    ),
    _row(
        catalog_key="ark-doubao-1-5-ui-tars-250428",
        label="豆包 1.5 UI-TARS（250428）",
        description="doubao-1-5-ui-tars-250428",
        model_id="doubao-1-5-ui-tars-250428",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["UI", "界面", "多模态"],
        scope_summary="界面/控件理解向模型；以控制台展示名为准。",
        canvas_node_kinds=list(_ALL),
        sort_order=27,
    ),
    _row(
        catalog_key="ark-doubao-1-5-lite-32k-250115",
        label="豆包 1.5 Lite 32K（250115）",
        description="doubao-1-5-lite-32k-250115",
        model_id="doubao-1-5-lite-32k-250115",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量", "32K", "高性价比"],
        scope_summary="32K 上下文轻量模型。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=28,
    ),
    _row(
        catalog_key="ark-doubao-1-5-pro-32k-250115",
        label="豆包 1.5 Pro 32K（250115）",
        description="doubao-1-5-pro-32k-250115",
        model_id="doubao-1-5-pro-32k-250115",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["通用", "32K"],
        scope_summary="32K 上下文 Pro。",
        canvas_node_kinds=list(_ALL),
        sort_order=29,
    ),
    _row(
        catalog_key="ark-doubao-1-5-pro-256k-250115",
        label="豆包 1.5 Pro 256K（250115）",
        description="doubao-1-5-pro-256k-250115",
        model_id="doubao-1-5-pro-256k-250115",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["长上下文", "256K"],
        scope_summary="256K 长上下文 Pro。",
        canvas_node_kinds=list(_ALL),
        sort_order=30,
    ),
    _row(
        catalog_key="ark-kimi-k2-thinking-251104",
        label="Kimi K2 Thinking（251104）",
        description="kimi-k2-thinking-251104",
        model_id="kimi-k2-thinking-251104",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["推理", "长文本", "Kimi"],
        scope_summary="Kimi K2 Thinking；需账号已开通该模型，model 字符串以控制台为准。",
        canvas_node_kinds=list(_ALL),
        sort_order=31,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-thinking-250715",
        label="豆包 Seed 1.6 Thinking（250715）",
        description="doubao-seed-1-6-thinking-250715",
        model_id="doubao-seed-1-6-thinking-250715",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["推理", "思考链"],
        scope_summary="Seed 1.6 Thinking 变体。",
        canvas_node_kinds=list(_ALL),
        sort_order=32,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-251015",
        label="豆包 Seed 1.6（251015）",
        description="doubao-seed-1-6-251015",
        model_id="doubao-seed-1-6-251015",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["通用", "平衡"],
        scope_summary="控制台后缀 251015 的 Seed 1.6 基础版。",
        canvas_node_kinds=list(_ALL),
        sort_order=33,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-lite-251015",
        label="豆包 Seed 1.6 Lite（251015）",
        description="doubao-seed-1-6-lite-251015",
        model_id="doubao-seed-1-6-lite-251015",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量", "高性价比"],
        scope_summary="与旧版「Seed 1.6 Lite」可能为不同迭代；以控制台 id 为准。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=34,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-flash-250828",
        label="豆包 Seed 1.6 Flash（250828）",
        description="doubao-seed-1-6-flash-250828",
        model_id="doubao-seed-1-6-flash-250828",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["低延迟", "高频"],
        scope_summary="Seed 1.6 Flash。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=35,
    ),
    _row(
        catalog_key="ark-doubao-seed-1-6-vision-250815",
        label="豆包 Seed 1.6 Vision（250815）",
        description="doubao-seed-1-6-vision-250815",
        model_id="doubao-seed-1-6-vision-250815",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["多模态", "看图"],
        scope_summary="Seed 1.6 视觉版。",
        canvas_node_kinds=list(_ALL),
        sort_order=36,
    ),
    _row(
        catalog_key="ark-doubao-seed-code-preview-251028",
        label="豆包 Seed Code（preview-251028）",
        description="doubao-seed-code-preview-251028",
        model_id="doubao-seed-code-preview-251028",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "预览版"],
        scope_summary="控制台带 preview 后缀的 Seed Code。",
        canvas_node_kinds=list(_CHAT_TEXT),
        sort_order=37,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-code-preview-260215",
        label="豆包 Seed 2.0 Code（preview-260215）",
        description="doubao-seed-2-0-code-preview-260215",
        model_id="doubao-seed-2-0-code-preview-260215",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["代码", "预览版"],
        scope_summary="控制台 Seed 2.0 Code 预览迭代。",
        canvas_node_kinds=list(_ALL),
        sort_order=38,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-pro-260215",
        label="豆包 Seed 2.0 Pro（260215）",
        description="doubao-seed-2-0-pro-260215",
        model_id="doubao-seed-2-0-pro-260215",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["旗舰", "复杂推理"],
        scope_summary="带日期后缀的 Seed 2.0 Pro；与未标注日期的目录项可并存。",
        canvas_node_kinds=list(_ALL),
        sort_order=39,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-lite-260215",
        label="豆包 Seed 2.0 Lite（260215）",
        description="doubao-seed-2-0-lite-260215",
        model_id="doubao-seed-2-0-lite-260215",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["轻量", "高性价比"],
        scope_summary="带日期后缀的 Seed 2.0 Lite。",
        canvas_node_kinds=list(_ALL),
        sort_order=40,
    ),
    _row(
        catalog_key="ark-doubao-seed-2-0-mini-260215",
        label="豆包 Seed 2.0 Mini（260215）",
        description="doubao-seed-2-0-mini-260215",
        model_id="doubao-seed-2-0-mini-260215",
        category="cat_language",
        category_label="语言模型（方舟）",
        category_order=0,
        scopes=["超轻量", "高频"],
        scope_summary="带日期后缀的 Seed 2.0 Mini。",
        canvas_node_kinds=list(_NO_IMG),
        sort_order=41,
    ),
    # --- 向量 ---
    _row(
        catalog_key="ark-doubao-embedding",
        label="豆包 Embedding",
        description="Doubao-embedding",
        model_id="Doubao-embedding",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["RAG", "语义检索"],
        scope_summary="文本向量嵌入；方舟 v3 同一密钥，用于知识库与相似度。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-doubao-embedding-large",
        label="豆包 Embedding Large",
        description="Doubao-embedding-large",
        model_id="Doubao-embedding-large",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["高精度", "长文本"],
        scope_summary="大维度文本嵌入，更高语义精度。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=1,
    ),
    _row(
        catalog_key="ark-doubao-embedding-vision",
        label="豆包 Embedding Vision",
        description="Doubao-embedding-vision",
        model_id="Doubao-embedding-vision",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["多模态", "以图搜图"],
        scope_summary="图像+文本多模态嵌入，图文检索。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=2,
    ),
    _row(
        catalog_key="ark-doubao-embedding-vision-251215",
        label="豆包 Embedding Vision（251215）",
        description="doubao-embedding-vision-251215",
        model_id="doubao-embedding-vision-251215",
        category="cat_embedding",
        category_label="向量模型",
        category_order=100,
        scopes=["多模态", "以图搜图", "RAG"],
        scope_summary="控制台带日期后缀的多模态向量模型；与未标注后缀的 Vision 嵌入可二选一。",
        canvas_node_kinds=[],
        api_kind="ark_embedding",
        show_in_canvas_llm_nodes=False,
        sort_order=3,
    ),
    # --- 视觉生成 / 编辑 ---
    _row(
        catalog_key="ark-seedream-5-0-lite",
        label="Seedream 5.0 Lite",
        description="doubao-seedream-5-0-260128",
        model_id="doubao-seedream-5-0-260128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生图", "图生图"],
        scope_summary="画布「图片」节点文生图：走 Ark images.generate；需与控制台开通的模型 id 一致。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=0,
    ),
    _row(
        catalog_key="ark-seedream-4-5",
        label="Seedream 4.5",
        description="doubao-seedream-4-5-251128",
        model_id="doubao-seedream-4-5-251128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高质量", "海报", "电商图"],
        scope_summary="高质量文生图；走 Ark images.generate。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=1,
    ),
    _row(
        catalog_key="ark-seedream-4-0",
        label="Seedream 4.0",
        description="doubao-seedream-4-0-250828",
        model_id="doubao-seedream-4-0-250828",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["稳定", "快速出图"],
        scope_summary="经典文生图；走 Ark images.generate。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=2,
    ),
    _row(
        catalog_key="ark-seededit-3-0-i2i",
        label="SeedEdit 3.0 i2i",
        description="doubao-seededit-3-0-i2i",
        model_id="doubao-seededit-3-0-i2i",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["修图", "扩图", "风格迁移"],
        scope_summary="图生图编辑；画布侧暂未接 images 多图参数，请优先用文生图模型或控制台。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=3,
    ),
    _row(
        catalog_key="ark-seedance-2-0",
        label="Seedance 2.0",
        description="doubao-seedance-2-0-260128",
        model_id="doubao-seedance-2-0-260128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "异步任务"],
        scope_summary="画布「视频」节点文生视频：content_generation.tasks 创建后轮询直至成功。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=9,
    ),
    _row(
        catalog_key="ark-seedance-1-5-pro",
        label="Seedance 1.5 Pro",
        description="doubao-seedance-1-5-pro-251215",
        model_id="doubao-seedance-1-5-pro-251215",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "图生视频"],
        scope_summary="视频生成：短片、动态海报；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=10,
    ),
    _row(
        catalog_key="ark-seedance-1-0-pro-fast",
        label="Seedance 1.0 Pro Fast",
        description="doubao-seedance-1-0-pro-fast-251015",
        model_id="doubao-seedance-1-0-pro-fast-251015",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["低延迟", "短视频"],
        scope_summary="快速视频草稿；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=11,
    ),
    _row(
        catalog_key="ark-seedance-1-0-pro",
        label="Seedance 1.0 Pro",
        description="doubao-seedance-1-0-pro-250528",
        model_id="doubao-seedance-1-0-pro-250528",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高质量视频"],
        scope_summary="高质量视频；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=12,
    ),
    _row(
        catalog_key="ark-seedream-3-0-t2i",
        label="Seedream 3.0 t2i",
        description="doubao-seedream-3-0-t2i-250415",
        model_id="doubao-seedream-3-0-t2i-250415",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生图", "Seedream"],
        scope_summary="控制台 Doubao-Seedream-3.0-t2i | 250415；走 Ark images.generate。",
        canvas_node_kinds=["image"],
        api_kind="ark_image_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=13,
    ),
    _row(
        catalog_key="ark-seedance-2-0-fast",
        label="Seedance 2.0 Fast",
        description="doubao-seedance-2-0-fast-260128",
        model_id="doubao-seedance-2-0-fast-260128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "快速"],
        scope_summary="Seedance 2.0 快速版；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=14,
    ),
    _row(
        catalog_key="ark-seedance-1-0-lite-t2v",
        label="Seedance 1.0 Lite t2v",
        description="doubao-seedance-1-0-lite-t2v-250428",
        model_id="doubao-seedance-1-0-lite-t2v-250428",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "轻量"],
        scope_summary="文生视频轻量线路；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=15,
    ),
    _row(
        catalog_key="ark-seedance-1-0-lite-i2v",
        label="Seedance 1.0 Lite i2v",
        description="doubao-seedance-1-0-lite-i2v-250428",
        model_id="doubao-seedance-1-0-lite-i2v-250428",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["图生视频", "轻量"],
        scope_summary="图生视频轻量线路；异步轮询。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=16,
    ),
    _row(
        catalog_key="ark-doubao-video-seaweed-241128",
        label="豆包视频 · Seaweed（241128）",
        description="doubao-seaweed-241128",
        model_id="doubao-seaweed-241128",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["文生视频", "图生视频"],
        scope_summary="控制台「Doubao-视频生成-Seaweed | 241128」；若调用报模型不存在，请在控制台复制模型 ID 覆盖本项 model_id。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=17,
    ),
    _row(
        catalog_key="ark-wan2-1-14b-i2v-250225",
        label="Wan2.1-14B i2v",
        description="wan2-1-14b-i2v-250225",
        model_id="wan2-1-14b-i2v-250225",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["图生视频"],
        scope_summary="控制台 Wan2.1-14B | i2v-250225；以控制台复制 id 为准。",
        canvas_node_kinds=["video"],
        api_kind="ark_video_gen",
        show_in_canvas_llm_nodes=True,
        sort_order=18,
    ),
    _row(
        catalog_key="ark-seed3d-1-0",
        label="Seed3D 1.0",
        description="doubao-seed3d-1-0-250928",
        model_id="doubao-seed3d-1-0-250928",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["3D", "文生3D", "图生3D"],
        scope_summary="控制台 Doubao-Seed3D-1.0 | 250928；走 content_generation.tasks。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=19,
    ),
    _row(
        catalog_key="ark-seed3d-2-0",
        label="Seed3D 2.0",
        description="doubao-seed3d-2-0-260328",
        model_id="doubao-seed3d-2-0-260328",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["3D", "文生3D", "图生3D"],
        scope_summary="3D 资产生成：游戏与建模辅助。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=20,
    ),
    _row(
        catalog_key="ark-hyper3d-gen2",
        label="Hyper3D Gen2",
        description="hyper3d-gen2-260112",
        model_id="hyper3d-gen2-260112",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["3D", "快速资产"],
        scope_summary="轻量化快速 3D 原型。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=21,
    ),
    _row(
        catalog_key="ark-hitem3d-2-0",
        label="Hitem3D 2.0",
        description="hitem3d-2-0-251223",
        model_id="hitem3d-2-0-251223",
        category="cat_vision",
        category_label="图像/视频/3D（方舟）",
        category_order=200,
        scopes=["高精度3D"],
        scope_summary="高精度 3D 与工业设计向素材。",
        canvas_node_kinds=[],
        api_kind="ark_3d_gen",
        show_in_canvas_llm_nodes=False,
        sort_order=22,
    ),
    # --- 语音（独立 openspeech 等，不在画布 LLM 下拉展示）---
    _row(
        catalog_key="speech-doubao-tts",
        label="豆包 · 语音合成",
        description="Doubao-语音合成",
        model_id="Doubao-语音合成",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["TTS"],
        scope_summary="基础 TTS；需 openspeech appid+access_token，非方舟 chat 密钥。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=0,
    ),
    _row(
        catalog_key="speech-doubao-voice-clone",
        label="豆包 · 声音复刻",
        description="Doubao-声音复刻",
        model_id="Doubao-声音复刻",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["复刻音色"],
        scope_summary="参考音频生成专属音色；独立语音接口鉴权。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=1,
    ),
    _row(
        catalog_key="speech-doubao-asr-stream",
        label="豆包 · 流式语音识别",
        description="Doubao-流式语音识别",
        model_id="Doubao-流式语音识别",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["ASR", "实时"],
        scope_summary="实时语音转写；独立 ASR 接口。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=2,
    ),
    _row(
        catalog_key="speech-doubao-asr-file",
        label="豆包 · 录音文件识别",
        description="Doubao-录音文件识别",
        model_id="Doubao-录音文件识别",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["离线转写"],
        scope_summary="长音频/批量文件转文字。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=3,
    ),
    _row(
        catalog_key="speech-doubao-simultaneous-2",
        label="豆包 · 同声传译 2.0",
        description="Doubao-同声传译-2.0",
        model_id="Doubao-同声传译-2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["同传", "翻译"],
        scope_summary="实时语音翻译；独立接口与配额。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=4,
    ),
    _row(
        catalog_key="speech-doubao-voice-design",
        label="豆包 · 音色设计",
        description="Doubao-音色设计",
        model_id="Doubao-音色设计",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["音色描述"],
        scope_summary="文本描述生成定制音色。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=5,
    ),
    _row(
        catalog_key="speech-doubao-tts-2",
        label="豆包 · 语音合成 2.0",
        description="Doubao-语音合成-2.0",
        model_id="Doubao-语音合成-2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["TTS", "情感"],
        scope_summary="增强 TTS，更自然情感与语气。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=6,
    ),
    _row(
        catalog_key="speech-doubao-podcast",
        label="豆包 · 语音播客",
        description="Doubao-语音播客",
        model_id="Doubao-语音播客",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["多角色", "播客"],
        scope_summary="剧本/对话生成多角色语音。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=7,
    ),
    _row(
        catalog_key="speech-doubao-asr-file-2",
        label="豆包 · 录音文件识别 2.0",
        description="Doubao-录音文件识别2.0",
        model_id="Doubao-录音文件识别2.0",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["转写", "字幕"],
        scope_summary="增强版离线转写，低延迟高准确率。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=8,
    ),
    _row(
        catalog_key="speech-doubao-realtime-voice",
        label="豆包 · 实时语音交互",
        description="Doubao-实时语音交互",
        model_id="Doubao-实时语音交互",
        category="cat_speech",
        category_label="语音模型（独立接口）",
        category_order=400,
        scopes=["端到端", "语音对话"],
        scope_summary="实时语音输入+输出；专属实时接口。",
        canvas_node_kinds=[],
        route="openspeech",
        api_kind="openspeech",
        show_in_canvas_llm_nodes=False,
        sort_order=9,
    ),
]
