# Generated by Django 5.2.13 on 2026-04-20 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this workflow (null for system/global workflows)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flowly_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
