# Generated by Django 5.2.13 on 2026-04-21 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_add_workflow_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("provider", models.CharField(default="openai", max_length=20)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "input_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "output_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("node_name", models.CharField(blank=True, default="", max_length=100)),
                ("call_type", models.CharField(default="completion", max_length=50)),
                ("latency_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="ai_engine.workflowexecution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "created_at"],
                        name="ai_engine_c_workflo_29f20d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_engine_c_user_id_85bfca_idx",
                    ),
                    models.Index(
                        fields=["model", "created_at"],
                        name="ai_engine_c_model_f06535_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_engine_c_created_d63e41_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="File type: pdf, docx, txt, html, md, csv",
                        max_length=50,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_path",
                    models.CharField(
                        help_text="Storage path of the uploaded file", max_length=512
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("chunking", "Chunking"),
                            ("embedding", "Embedding"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if processing failed",
                    ),
                ),
                (
                    "chunk_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of chunks created from this document",
                    ),
                ),
                (
                    "embedding_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Document title (extracted from metadata)",
                        max_length=500,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Document author",
                        max_length=255,
                    ),
                ),
                (
                    "total_pages",
                    models.IntegerField(default=0, help_text="Total pages (for PDFs)"),
                ),
                (
                    "document_metadata",
                    models.JSONField(
                        default=dict, help_text="Additional document metadata (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flowly_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Document",
                "verbose_name_plural": "Knowledge Base Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "processing_status"],
                        name="ai_engine_d_workflo_ae3e26_idx",
                    ),
                    models.Index(
                        fields=["workflow", "embedding_status"],
                        name="ai_engine_d_workflo_d83457_idx",
                    ),
                ],
            },
        ),
    ]
