# Generated by Django 5.2.13 on 2026-04-22 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0003_costrecord_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flowly_conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_sessions",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_engine.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowGraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_edge_id", models.CharField(max_length=128)),
                (
                    "source_node_id",
                    models.CharField(
                        help_text="Matches WorkflowGraphNode.client_node_id",
                        max_length=128,
                    ),
                ),
                (
                    "target_node_id",
                    models.CharField(
                        help_text="Matches WorkflowGraphNode.client_node_id",
                        max_length=128,
                    ),
                ),
                ("source_handle", models.CharField(blank=True, max_length=64)),
                ("target_handle", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_id", "client_edge_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "client_edge_id"),
                        name="uniq_ai_engine_workflow_client_edge",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowGraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_node_id",
                    models.CharField(
                        help_text="Stable id from the visual editor (e.g. Vue Flow node id).",
                        max_length=128,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("ai_chat", "AI Chat"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("position_x", models.FloatField(default=0.0)),
                ("position_y", models.FloatField(default=0.0)),
                ("z_index", models.IntegerField(default=0)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Node parameters (no secrets — placeholders only until wired up).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_id", "client_node_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "client_node_id"),
                        name="uniq_ai_engine_workflow_client_node",
                    )
                ],
            },
        ),
    ]
