# Generated by Django 5.2.13 on 2026-04-22 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0004_workflow_graph_and_conversation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "对话消息",
                "verbose_name_plural": "对话消息",
            },
        ),
        migrations.AlterModelOptions(
            name="conversationsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
            },
        ),
        migrations.AlterModelOptions(
            name="workflowgraphedge",
            options={
                "ordering": ["workflow_id", "client_edge_id"],
                "verbose_name": "工作流图边",
                "verbose_name_plural": "工作流图边",
            },
        ),
        migrations.AlterModelOptions(
            name="workflowgraphnode",
            options={
                "ordering": ["workflow_id", "client_node_id"],
                "verbose_name": "工作流图节点",
                "verbose_name_plural": "工作流图节点",
            },
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="attachments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="每项建议为 dict，至少包含 type 与 url 或 storage_key。",
                verbose_name="附件列表",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="纯文本或多模态占位文本；结构化输出可用 JSON 字符串。",
                verbose_name="正文",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="如 token 用量、模型名、链路 trace_id；勿存密钥。",
                verbose_name="消息级元数据",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="role",
            field=models.CharField(
                choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")],
                help_text="决定该条在上下文拼接中的语义。",
                max_length=16,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="session",
            field=models.ForeignKey(
                help_text="会话删除时级联删除其下所有消息。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_engine.conversationsession",
                verbose_name="所属会话",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="渠道、标签、优先级等业务字段；避免存放明文 PII。",
                verbose_name="扩展元数据",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="topic",
            field=models.CharField(
                blank=True,
                help_text="便于列表展示；可由首条用户消息摘要自动生成。",
                max_length=255,
                verbose_name="会话主题/标题",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="匿名访客可为空；登录后建议补上以便审计与配额统计。",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flowly_conversation_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="若设置，自动回复可优先按该工作流的 LangGraph 定义执行。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation_sessions",
                to="ai_engine.workflow",
                verbose_name="关联工作流",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="client_edge_id",
            field=models.CharField(
                help_text="与编辑器中 edge.id 一致，在同一 workflow 内唯一。",
                max_length=128,
                verbose_name="前端边 ID",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="如条件路由标签、权重、动画状态等；勿存密钥。",
                verbose_name="边附加信息",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="source_handle",
            field=models.CharField(
                blank=True,
                help_text="多输出端口时用字符串区分；无多端口时可留空。",
                max_length=64,
                verbose_name="源端口/句柄",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="source_node_id",
            field=models.CharField(
                help_text="等于某一 WorkflowGraphNode.client_node_id，否则图为脏数据。",
                max_length=128,
                verbose_name="源节点前端 ID",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="target_handle",
            field=models.CharField(
                blank=True,
                help_text="多输入端口时区分连接点；单输入可留空。",
                max_length=64,
                verbose_name="目标端口/句柄",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="target_node_id",
            field=models.CharField(
                help_text="等于某一 WorkflowGraphNode.client_node_id。",
                max_length=128,
                verbose_name="目标节点前端 ID",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="workflowgraphedge",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_edges",
                to="ai_engine.workflow",
                verbose_name="所属工作流",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="client_node_id",
            field=models.CharField(
                help_text="与 Vue Flow 等编辑器中的 node.id 一致，在同一 workflow 内唯一。",
                max_length=128,
                verbose_name="前端节点 ID",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="非敏感配置 JSON：如 temperature、模板名、端口开关等；勿存密钥。",
                verbose_name="节点参数",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("audio", "音频"),
                    ("image", "图片"),
                    ("video", "视频"),
                    ("ai_chat", "AI 对话"),
                    ("custom", "自定义"),
                ],
                default="custom",
                help_text="决定运行时选用哪个 NodeExecutor 或与 LangGraph 节点的映射关系。",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="position_x",
            field=models.FloatField(
                default=0.0,
                help_text="编辑器坐标系下的水平位置，具体原点由前端约定。",
                verbose_name="画布 X 坐标",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="position_y",
            field=models.FloatField(
                default=0.0,
                help_text="编辑器坐标系下的垂直位置。",
                verbose_name="画布 Y 坐标",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="画布上展示用，可不填；与业务主键无关。",
                max_length=255,
                verbose_name="显示标题",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="workflow",
            field=models.ForeignKey(
                help_text="删除工作流时级联删除其下所有节点与边（见 WorkflowGraphEdge）。",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_nodes",
                to="ai_engine.workflow",
                verbose_name="所属工作流",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="z_index",
            field=models.IntegerField(
                default=0,
                help_text="节点重叠时的绘制顺序，数值越大越靠前。",
                verbose_name="叠放层级",
            ),
        ),
    ]
