# Generated by Django 5.2.13 on 2026-04-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0005_alter_conversationmessage_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustomNodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL 安全短名，便于展示；与 user 组合唯一。",
                        max_length=64,
                        verbose_name="类型标识",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=128, verbose_name="显示名称"),
                ),
                (
                    "provider_route",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI 兼容"),
                            ("claude", "Anthropic Claude"),
                            ("ollama", "Ollama 本地"),
                            ("vectorengine", "VectorEngine 兼容网关"),
                        ],
                        help_text="与 ``workflow.get_chat_model`` 的 model_name 参数一致。",
                        max_length=32,
                        verbose_name="模型路由",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="前端仅填写模型 id 字符串，如 gpt-4o、claude-3-5-sonnet-20241022。",
                        max_length=128,
                        verbose_name="模型名",
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="temperature、max_tokens 等；勿存密钥。",
                        verbose_name="默认节点参数",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "用户自定义节点类型",
                "verbose_name_plural": "用户自定义节点类型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="costrecord",
            name="client_node_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="与 ``WorkflowGraphNode.client_node_id`` 对齐，用于按画布节点聚合费用。",
                max_length=128,
                verbose_name="画布节点 ID",
            ),
        ),
        migrations.AddField(
            model_name="costrecord",
            name="conversation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="自动回复等场景按会话计费时填写；可与 execution 并存。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_records",
                to="ai_engine.conversationsession",
                verbose_name="对话会话",
            ),
        ),
        migrations.AlterField(
            model_name="costrecord",
            name="node_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LangGraph 逻辑节点名；与 client_node_id 可同时使用。",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workflowgraphnode",
            name="node_type",
            field=models.CharField(
                db_index=True,
                default="custom",
                help_text="内置类型或用户自定义 ut_<id>；由 ``workflow_nodes`` 注册表解析执行器。",
                max_length=64,
                verbose_name="节点类型",
            ),
        ),
        migrations.AddIndex(
            model_name="costrecord",
            index=models.Index(
                fields=["conversation_session", "created_at"],
                name="ai_engine_c_convers_ea9b04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costrecord",
            index=models.Index(
                fields=["workflow", "client_node_id", "created_at"],
                name="ai_engine_c_workflo_8a2486_idx",
            ),
        ),
        migrations.AddField(
            model_name="usercustomnodetype",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_node_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercustomnodetype",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="uniq_user_custom_node_slug"
            ),
        ),
    ]
