# Generated by Django 5.2.13 on 2026-04-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0006_user_custom_node_and_cost_dims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustomnodetype",
            name="provider_route",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI 兼容"),
                    ("doubao", "火山方舟 / 豆包"),
                    ("ark", "方舟（同 doubao）"),
                    ("claude", "Anthropic Claude"),
                    ("ollama", "Ollama 本地"),
                    ("vectorengine", "VectorEngine 兼容网关"),
                ],
                help_text="与 ``workflow.get_chat_model`` 的 model_name 参数一致。",
                max_length=32,
                verbose_name="模型路由",
            ),
        ),
    ]
