# Generated by Django 5.2.13 on 2026-04-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0007_user_custom_provider_doubao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Workflow definition this thread uses",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="ai_engine.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="ai_engine.workflow",
            ),
        ),
    ]
