# Generated by Django 5.2.13 on 2026-04-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0008_alter_thread_workflow_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowGraphValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=False, help_text="是否通过校验。"),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True, default=list, help_text="校验错误列表（JSON）。"
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.OneToOneField(
                        help_text="所属工作流（唯一）。",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_validation",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptEnhancementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_node_id",
                    models.CharField(
                        blank=True,
                        help_text="画布节点 id（与 EditorNode.id 一致；可为空）。",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        blank=True,
                        help_text="节点类型（如 chat/text/ut_<id>；可为空）。",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="被加工的字段名（如 systemPrompt / prompt / captionPrompt）。",
                        max_length=64,
                    ),
                ),
                (
                    "raw_prompt",
                    models.TextField(help_text="用户原始输入（待加工文本）。"),
                ),
                (
                    "instruction",
                    models.TextField(
                        blank=True, help_text="用户额外加工要求（可为空）。", null=True
                    ),
                ),
                (
                    "candidates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="模型生成的候选列表（JSON）。",
                    ),
                ),
                (
                    "suggested_text",
                    models.TextField(
                        blank=True, help_text="系统默认建议的候选（可为空）。"
                    ),
                ),
                (
                    "selected_text",
                    models.TextField(
                        blank=True,
                        help_text="用户最终确认的文本（确认前可为空）。",
                        null=True,
                    ),
                ),
                (
                    "provider_route",
                    models.CharField(
                        help_text="模型路由（openai/doubao/claude/ollama/vectorengine）。",
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="模型 id（如 gpt-4o 或 ep-xxxx）。", max_length=128
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="采样温度（可为空）。", null=True
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, help_text="max_tokens（可为空）。", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="触发本次加工的用户；匿名/系统任务可为空。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_enhancement_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="所属工作流上下文；不绑定工作流时可为空。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompt_enhancement_records",
                        to="ai_engine.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "created_at"],
                        name="ai_engine_p_workflo_d1172d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_engine_p_user_id_e0ee28_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_engine_p_created_09c992_idx"
                    ),
                ],
            },
        ),
    ]
