# Generated by Django 5.x

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_engine", "0011_uilabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChatModelPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=128, verbose_name="显示名称")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI 兼容"),
                            ("doubao", "火山方舟 / 豆包"),
                            ("ark", "方舟（同 doubao）"),
                            ("claude", "Anthropic Claude"),
                            ("ollama", "Ollama 本地"),
                            ("vectorengine", "VectorEngine 兼容网关"),
                        ],
                        help_text="与 ``workflow.get_chat_model`` 的路由名一致。",
                        max_length=32,
                        verbose_name="模型路由",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="如方舟 ep-…、OpenAI 的 gpt-4o 等；勿写入密钥。",
                        max_length=256,
                        verbose_name="模型 ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_model_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户聊天模型预设",
                "verbose_name_plural": "用户聊天模型预设",
                "ordering": ["-updated_at"],
            },
        ),
    ]
