# Generated by Django 5.2.13 on 2026-04-24 01:48

from django.db import migrations, models


def seed_aimodel_catalog(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    from ai_engine.catalog_seed import CATALOG_SEED_ROWS

    for raw in CATALOG_SEED_ROWS:
        data = dict(raw)
        ck = data.pop("catalog_key")
        AIModelCatalogEntry.objects.update_or_create(catalog_key=ck, defaults=data)


def unseed_aimodel_catalog(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    from ai_engine.catalog_seed import CATALOG_SEED_ROWS

    AIModelCatalogEntry.objects.filter(
        catalog_key__in=[r["catalog_key"] for r in CATALOG_SEED_ROWS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0013_userchatmodelpreset_scope_and_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalog_key",
                    models.SlugField(max_length=96, unique=True, verbose_name="目录键"),
                ),
                ("label", models.CharField(max_length=160, verbose_name="展示名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, verbose_name="短说明"),
                ),
                (
                    "route",
                    models.CharField(
                        default="doubao",
                        help_text="与 get_chat_model 路由一致；语音独立接口可填 openspeech（仅元数据标记）。",
                        max_length=32,
                        verbose_name="路由",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        blank=True,
                        help_text="方舟 OpenAI 兼容调用时的 model；空则回退环境默认（一般仅用于占位）。",
                        max_length=256,
                        verbose_name="模型 ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="分类 id"
                    ),
                ),
                (
                    "category_label",
                    models.CharField(max_length=128, verbose_name="分类展示名"),
                ),
                (
                    "category_order",
                    models.IntegerField(default=500, verbose_name="分类排序"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="同分类内排序"
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "scope_summary",
                    models.TextField(blank=True, verbose_name="详细说明"),
                ),
                (
                    "canvas_node_kinds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='如 ["chat","text"]；空且非 canvas_universal 表示不限制（一般不用）。',
                        verbose_name="画布 LLM 节点类型",
                    ),
                ),
                (
                    "canvas_universal",
                    models.BooleanField(
                        default=False, verbose_name="全画布 LLM 节点可选"
                    ),
                ),
                (
                    "api_kind",
                    models.CharField(
                        choices=[
                            ("ark_chat", "方舟对话/补全"),
                            ("ark_embedding", "方舟向量嵌入"),
                            ("ark_image_gen", "方舟图像生成/编辑"),
                            ("ark_video_gen", "方舟视频生成"),
                            ("ark_3d_gen", "方舟 3D 生成"),
                            ("openspeech", "火山语音（独立接口）"),
                        ],
                        db_index=True,
                        default="ark_chat",
                        max_length=32,
                        verbose_name="接口类型",
                    ),
                ),
                (
                    "show_in_canvas_llm_nodes",
                    models.BooleanField(
                        default=True,
                        help_text="向量/文生图/语音等非对话补全能力选 False，仍出现在 GET /api/ai/models 供其它功能使用。",
                        verbose_name="在画布 LLM 节点展示",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 模型目录项",
                "verbose_name_plural": "AI 模型目录",
                "ordering": ["category_order", "sort_order", "catalog_key"],
            },
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="api_base_url",
            field=models.CharField(
                blank=True,
                help_text="可选；OpenAI/方舟/VectorEngine 等兼容接口的 base，留空用环境默认。",
                max_length=512,
                verbose_name="API Base URL",
            ),
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="api_key_encrypted",
            field=models.TextField(
                blank=True,
                help_text="Fernet 密文；留空则调用时使用环境变量中的密钥。",
                verbose_name="API 密钥（加密）",
            ),
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="category",
            field=models.CharField(
                default="user_custom",
                help_text="建议按「用途」命名（如 fn_high_volume），与内置 ``ai_model_catalog`` 的 category 同形，便于前端与内置项一起分组。",
                max_length=32,
                verbose_name="功能分类 id",
            ),
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="category_label",
            field=models.CharField(
                default="我的模型", max_length=128, verbose_name="功能分类展示名"
            ),
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="model_id",
            field=models.CharField(
                help_text="如方舟 ep-…、OpenAI 的 gpt-4o 等。",
                max_length=256,
                verbose_name="模型 ID",
            ),
        ),
        migrations.AlterField(
            model_name="userchatmodelpreset",
            name="scope_summary",
            field=models.TextField(
                blank=True,
                help_text="一段话说明该模型适合做什么；展示在模型选择器下方。",
                verbose_name="适用范围说明",
            ),
        ),
        migrations.RunPython(seed_aimodel_catalog, unseed_aimodel_catalog),
    ]
