# Generated by Cursor for AI 自动回复 + 主导航文案

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_autoreply_nav_label(apps, schema_editor):
    UILabel = apps.get_model("ai_engine", "UILabel")
    UILabel.objects.update_or_create(
        locale="zh-CN",
        key="app.nav.autoReply",
        defaults={
            "value": "AI 自动回复",
            "category": "app",
            "description": "主导航",
        },
    )


def noop_reverse(apps, schema_editor):
    UILabel = apps.get_model("ai_engine", "UILabel")
    UILabel.objects.filter(locale="zh-CN", key="app.nav.autoReply").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_engine", "0014_aimodelcatalogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReplyRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="规则名称")),
                ("system_prompt", models.TextField(help_text="描述语气、业务边界、输出格式等；模型将据此生成对用户消息的回复。", verbose_name="系统提示")),
                (
                    "model_key",
                    models.CharField(
                        blank=True,
                        help_text="与画布 modelKey 一致；留空则使用服务端 FLOWLY_AUTO_REPLY_MODEL_KEY。",
                        max_length=96,
                        verbose_name="模型目录键",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动回复规则",
                "verbose_name_plural": "自动回复规则",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AutoReplyJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("processing", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("input_text", models.TextField(verbose_name="用户/客户消息")),
                ("reply_text", models.TextField(blank=True, verbose_name="模型回复")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("model_key_used", models.CharField(blank=True, max_length=96, verbose_name="实际使用的模型键")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="ai_engine.autoreplyrule",
                        verbose_name="使用的规则",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "自动回复任务",
                "verbose_name_plural": "自动回复任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="autoreplyjob",
            index=models.Index(fields=["user", "created_at"], name="ai_arj_user_created_idx"),
        ),
        migrations.RunPython(add_autoreply_nav_label, noop_reverse),
    ]
