# Generated by Django 5.2.13 on 2026-04-24 06:58

from django.db import migrations


def forwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    fixes = {
        "ark-seedance-1-5-pro": "doubao-seedance-1-5-pro-251215",
        "ark-seedance-1-0-pro-fast": "doubao-seedance-1-0-pro-fast-251015",
        "ark-seedance-1-0-pro": "doubao-seedance-1-0-pro-250528",
    }
    for ck, mid in fixes.items():
        AIModelCatalogEntry.objects.filter(catalog_key=ck).update(
            model_id=mid,
            description=mid,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0020_sync_vision_catalog_for_canvas"),
    ]

    operations = [
        migrations.RunPython(forwards, noop_reverse),
    ]
