# Generated by Cursor on 2026-04-24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0020_workflow_soft_delete"),
        ("ai_engine", "0021_seedance_model_id_fix"),
    ]

    operations = []

