# Generated by Django migration helper

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0025_localmediaasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoreplyscreenprofile",
            name="agent_runtime_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="由本机屏幕代理周期性写入：区域是否识别到、是否检测到消息变化、最近 OCR 摘要等；前端监控页只读展示。",
                verbose_name="本机代理运行快照",
            ),
        ),
    ]
