# Generated by Cursor on 2026-04-26

from django.db import migrations


def forwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    # 与方舟官方示例一致：contents/generations/tasks 的 model 字段
    AIModelCatalogEntry.objects.filter(catalog_key="ark-seed3d-2-0").update(
        model_id="doubao-seed3d-2-0-260328",
        description="doubao-seed3d-2-0-260328",
    )


def backwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    AIModelCatalogEntry.objects.filter(catalog_key="ark-seed3d-2-0").update(
        model_id="Doubao-Seed3D-2.0",
        description="Doubao-Seed3D-2.0",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0028_aimodelvariant"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
