# Generated by Cursor on 2026-04-26 — 同步控制台列出的 model_id 到 AIModelCatalogEntry

from django.db import migrations

# 与 catalog_seed.CATALOG_SEED_ROWS 中本批次新增项一致（迁移只跑一次的 upsert）
_NEW_CATALOG_KEYS: frozenset[str] = frozenset(
    {
        "ark-deepseek-v3-1-terminus",
        "ark-deepseek-r1-250528",
        "ark-deepseek-v3-250324",
        "ark-doubao-1-5-thinking-pro-250415",
        "ark-doubao-1-5-vision-pro-250328",
        "ark-doubao-1-5-ui-tars-250428",
        "ark-doubao-1-5-lite-32k-250115",
        "ark-doubao-1-5-pro-32k-250115",
        "ark-doubao-1-5-pro-256k-250115",
        "ark-kimi-k2-thinking-251104",
        "ark-doubao-seed-1-6-thinking-250715",
        "ark-doubao-seed-1-6-251015",
        "ark-doubao-seed-1-6-lite-251015",
        "ark-doubao-seed-1-6-flash-250828",
        "ark-doubao-seed-1-6-vision-250815",
        "ark-doubao-seed-code-preview-251028",
        "ark-doubao-seed-2-0-code-preview-260215",
        "ark-doubao-seed-2-0-pro-260215",
        "ark-doubao-seed-2-0-lite-260215",
        "ark-doubao-seed-2-0-mini-260215",
        "ark-doubao-embedding-vision-251215",
        "ark-seedream-3-0-t2i",
        "ark-seedance-2-0-fast",
        "ark-seedance-1-0-lite-t2v",
        "ark-seedance-1-0-lite-i2v",
        "ark-doubao-video-seaweed-241128",
        "ark-wan2-1-14b-i2v-250225",
        "ark-seed3d-1-0",
    }
)


def forwards(apps, schema_editor):
    from ai_engine.catalog_seed import CATALOG_SEED_ROWS

    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    by_key = {r["catalog_key"]: r for r in CATALOG_SEED_ROWS}
    for ck in sorted(_NEW_CATALOG_KEYS):
        raw = by_key.get(ck)
        if not raw:
            continue
        data = dict(raw)
        ck2 = data.pop("catalog_key")
        AIModelCatalogEntry.objects.update_or_create(catalog_key=ck2, defaults=data)


def backwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    AIModelCatalogEntry.objects.filter(catalog_key__in=_NEW_CATALOG_KEYS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0029_seed3d_model_id_fix"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
