# Generated by Cursor on 2026-04-26 — 方舟 3D 官方 model 字段（与 catalog_seed 一致）

from django.db import migrations


def forwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    AIModelCatalogEntry.objects.filter(catalog_key="ark-hyper3d-gen2").update(
        model_id="hyper3d-gen2-260112",
        description="hyper3d-gen2-260112",
    )
    AIModelCatalogEntry.objects.filter(catalog_key="ark-hitem3d-2-0").update(
        model_id="hitem3d-2-0-251223",
        description="hitem3d-2-0-251223",
    )


def backwards(apps, schema_editor):
    AIModelCatalogEntry = apps.get_model("ai_engine", "AIModelCatalogEntry")
    AIModelCatalogEntry.objects.filter(catalog_key="ark-hyper3d-gen2").update(
        model_id="Hyper3D-Gen2",
        description="Hyper3D-Gen2",
    )
    AIModelCatalogEntry.objects.filter(catalog_key="ark-hitem3d-2-0").update(
        model_id="Hitem3D-2.0",
        description="Hitem3D-2.0",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0030_catalog_seed_console_models"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
