# Generated by Django 5.2.13 on 2026-04-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkpoint", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="checkpoint",
            name="unique_checkpoint",
        ),
    ]
